apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: bookstore-management-db           # Name of the Kubernetes resource
spec:
  replicas: 1
  strategy:
    type: Recreate                     # Number of pods to run at any given time
  selector:
    matchLabels:
      app: bookstore-management
      tier: mysql        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: bookstore-management
        tier: mysql 
    spec:                        # Spec for the container which will run in the Pod
      containers:
        - image: mysql:5.7                  # The container image
          name: mysql
          imagePullPolicy: "IfNotPresent"   # Get it from dockerhub if it is not present in our machine
          envFrom:                                # Environment variables passed to the container 
          - secretRef:                            # Read environment variables from kubernetes secrets
              name: mysql-secret

          ports:
          - containerPort: 3306             # The port that the container exposes 
            name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage # This name should match the name specified in `volumes.name`
      volumes:                        # A PersistentVolume is mounted as a volume to the Pod  
      - name: mysql-persistent-storage 
        persistentVolumeClaim:
          claimName: mysql-pv-claim
