apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  DB: bookStore
  TEST_DB: bookStoreTest
  DB_DRIVER: sql
  DB_SOURCE_SQL_IMAGE: root:password@tcp(bookstore-management-db-service:3306)/bookStore?charset=utf8mb4&parseTime=True&loc=Local
  DB_SOURCE: root:password@tcp(bookstore-management-db-service:3306)/
  DB_SOURCE_DB: root:password@tcp(bookstore-management-db-service:3306)/bookStore?charset=utf8mb4&parseTime=True&loc=Local
  MYSQL_ROOT_PASSWORD: password
